// Generated by CoffeeScript 1.8.0
(function() {
  var fileinfo;

  fileinfo = $('.fileinfo');

  fileinfo.each(function() {
    var filename, orighref, swfName;
    orighref = $(this).children('a');
    orighref = orighref.attr("href");
    orighref = orighref.replace('media.', '');
    filename = $('.unimportant > a', this);
    swfName = filename.attr("download");
    if (swfName.match(/\.swf$/)) {
      return $(this).append(' <a class="swfdownload" download="' + swfName + '" href="' + orighref + '">[Download]</a>');
    }
  });

}).call(this);
