// Generated by CoffeeScript 1.8.0
(function() {
  var fileinfo;

  fileinfo = $('.fileinfo');

  fileinfo.each(function() {
    var filename, orighref, swfName;
    filename = $('.postfilename', this);
    orighref = $(this).children('a');
    orighref = orighref.attr("href");
    if (filename.attr("title")) {
      swfName = filename.attr("title");
    } else {
      swfName = filename.text();
    }
    if (swfName.match(/\.swf$/)) {
      return $(this).append(' <a class="swfdownload" download="' + swfName + '" href="' + orighref + '">[Download]</a>');
    }
  });

}).call(this);
