// Generated by CoffeeScript 1.8.0
(function() {
  var fileinfo;

  fileinfo = $('.fileinfo');

  fileinfo.each(function() {
    var filename, orighref, swfName;
    orighref = $(this).children('a');
    orighref = orighref.attr("href");
    filename = $('.unimportant > a', this);
    swfName = filename.attr("download");
    if (swfName.match(/\.swf$/)) {

      /*Move the line below to above the "if" statement if you want it to apply to all files, not just swfs. */
      $(this).append(' <a class="swfdownload" download="' + swfName + '" href="' + orighref + '">[Download]</a>');
      return $(this).append(' <a class="swfsauce" href="http://eye.swfchan.com/search/?q=' + swfName + '" target="_blank">[Check Sauce on SWFCHAN]</a>');
    }
  });

}).call(this);
