// Generated by CoffeeScript 1.8.0
(function() {
  var fileinfo;

  fileinfo = $('.fileinfo');

  fileinfo.each(function() {
    var filename, swfName;
    filename = $('.postfilename', this);
    swfName = filename.attr("title");
    if (swfName.match(/\.swf$/)) {
      return $(this).append(' <a class="swfsauce" href="http://eye.swfchan.com/search/?q=' + swfName + '" target="_blank">[Check Sauce on SWFCHAN]</a>');
    }
  });

}).call(this);
